--- 
## this playbook require community such modules
## ansible-galaxy collection install ansible.posix
## ansible-galaxy collection install community.general
- name: increase kernel open file max
  hosts: webservers
  vars: 
    my_domain: ec2-user
    sysctl_file_max: '524288'
    user_file_max:  '262144'
    user_nproc_max: '10240'

  #  remote_user: root
  become: true ## this includes usernames, groups, guid ranges etc

  tasks:
  - name: Set kernel file max
    ansible.posix.sysctl:
        name: fs.file-max
        value: "{{ sysctl_file_max }}"
        sysctl_set: yes
        state: present
        reload: yes
  - name: listen backlog
    ansible.posix.sysctl:
        name: net.core.somaxconn
        value: '4096'
  - name: max number of time wait sockets
    ansible.posix.sysctl:
        name: net.ipv4.tcp_max_tw_buckets
        value: '65536'

###  - name: ensure kernel open max parameter to large
###     lineinfile:
###             path: /etc/sysctl.conf
###             state: present
###             line: 'fs.file-max = {{ sysctl_file_max }}'
###
  - name: ensure user file max the large number
    pam_limits:
        domain: "{{ my_domain }}"
        limit_type: "{{ item }}"
        limit_item: nofile
        value:  "{{ user_file_max }}"
    loop:
        - hard
        - soft

  - name: ensure user number of process soft max the large number
    pam_limits:
        domain: "{{ my_domain }}"
        limit_type: "{{ item }}"
        limit_item: nproc
        value:  "{{ user_nproc_max }}"
    loop:
        - hard
        - soft
